-- 清空測試資料，準備重新測試
TRUNCATE TABLE psa_card_details CASCADE;
TRUNCATE TABLE psa_orders CASCADE;
TRUNCATE TABLE payments CASCADE;
TRUNCATE TABLE product_catalog CASCADE;
TRUNCATE TABLE break_credits CASCADE;
TRUNCATE TABLE breaks CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE users CASCADE;
