-- 新增 password 欄位到 users 表
ALTER TABLE users ADD COLUMN IF NOT EXISTS password VARCHAR(4);

-- 停用所有表的 RLS 以便資料遷移
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE breaks DISABLE ROW LEVEL SECURITY;
ALTER TABLE break_credits DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE shipments DISABLE ROW LEVEL SECURITY;
ALTER TABLE psa_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE psa_card_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_catalog DISABLE ROW LEVEL SECURITY;
